"""
edsim.roadmap.generator -- Roadmap document generator.

Assembles architecture, questions, dependencies, milestones, and
manuscript outline into a single Markdown roadmap document.
"""

from __future__ import annotations

from pathlib import Path

from .architecture import build_edsim3_architecture
from .questions import list_research_questions, questions_by_theme
from .dependencies import build_dependency_graph
from .milestones import build_milestone_plan
from .manuscript import build_edsim3_manuscript_outline


def generate_roadmap(
    output_path: str = "manuscript/ED-SIM-03-Roadmap.md",
) -> str:
    """Generate the complete ED-SIM-03 roadmap document.

    Parameters
    ----------
    output_path : str
        Path to write the roadmap.

    Returns
    -------
    str
        Path to the written file.
    """
    arch = build_edsim3_architecture()
    questions = list_research_questions()
    graph = build_dependency_graph(arch, questions)
    plan = build_milestone_plan(graph)
    outline = build_edsim3_manuscript_outline()

    sections = [
        "# ED-SIM-03 Roadmap",
        "",
        arch.description,
        f"  Target version: {arch.version}",
        "",
        "---",
        "",
        "## 1. Architecture",
        "",
        f"{len(arch.components)} components are planned:",
        "",
        "| Component | Title | Prerequisites |",
        "|-----------|-------|---------------|",
    ]
    for c in arch.components:
        prereqs = ", ".join(c.prerequisites) if c.prerequisites else "(none)"
        sections.append(f"| {c.name} | {c.title} | {prereqs} |")

    sections.extend(["", "### Component Details", ""])
    for c in arch.components:
        sections.append(f"#### {c.title} (`{c.name}`)")
        sections.append("")
        sections.append(c.description)
        sections.append("")
        sections.append(f"**Motivation:** {c.motivation}")
        sections.append("")
        if c.risks:
            sections.append("**Risks:**")
            for r in c.risks:
                sections.append(f"- {r}")
            sections.append("")
        if c.outputs:
            sections.append("**Outputs:** " + ", ".join(c.outputs))
            sections.append("")

    # Questions
    sections.extend(["---", "", "## 2. Research Questions", ""])
    by_theme = questions_by_theme()
    for theme, qs in by_theme.items():
        sections.append(f"### {theme}")
        sections.append("")
        for q in qs:
            deps = ", ".join(q.dependencies) if q.dependencies else "(none)"
            sections.append(
                f"**{q.id}** [{q.difficulty}]: {q.question}"
            )
            sections.append(f"  Rationale: {q.rationale}")
            sections.append(f"  Dependencies: {deps}")
            sections.append("")

    # Dependency graph
    sections.extend([
        "---",
        "",
        "## 3. Dependency Graph",
        "",
        f"{len(graph.nodes)} nodes, {len(graph.edges)} edges.",
        "",
        graph.to_table(),
        "",
        "### Mermaid Diagram",
        "",
        "```mermaid",
        graph.to_mermaid(),
        "```",
        "",
    ])

    # Milestones
    sections.extend(["---", "", "## 4. Milestone Plan", ""])
    sections.append(plan.to_table())
    sections.append("")
    sections.append(plan.to_detailed_markdown())

    # Manuscript outline
    sections.extend(["---", "", "## 5. Manuscript Outline", ""])
    sections.append(outline.to_markdown())

    # Summary
    sections.extend([
        "---",
        "",
        "## 6. Summary",
        "",
        f"ED-SIM-03 comprises {len(arch.components)} components, "
        f"{len(questions)} research questions, "
        f"{len(graph.edges)} dependencies, and "
        f"{len(plan.milestones)} development phases.",
        "",
        "The closest framework (statistical mechanics, score 12/15) "
        "provides the starting point for the experimental bridge.  "
        "The seven unique ED features drive the core research agenda.",
        "",
        "This roadmap is auto-generated by `edsim.roadmap.generator` "
        "and can be updated as components are completed.",
    ])

    content = "\n".join(sections)
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")

    return str(out)
